# Generated by Django 5.2.8 on 2025-12-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_comment_lessoncomment_lessonrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncomment',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='teacher_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
