# Generated by Django 6.0.5 on 2026-06-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='lessons/materials/'),
        ),
    ]
