# Generated by Django 6.0.5 on 2026-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='submitted_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
