# Generated by Django 5.2.8 on 2026-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='student_recitations/')),
                ('recognized_text', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wrong_words', models.JSONField(blank=True, default=list)),
                ('comparison', models.JSONField(blank=True, default=list)),
                ('statistics', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurahAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_ar', models.CharField(max_length=100)),
                ('reciter_en', models.CharField(max_length=100)),
                ('rewaya_ar', models.CharField(max_length=100)),
                ('rewaya_en', models.CharField(max_length=100)),
                ('server', models.URLField()),
                ('audio_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
