# Generated by Django 5.2.8 on 2025-12-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TafsirSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran_app.surah')),
            ],
            options={
                'unique_together': {('surah', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TafsirVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_app.tafsirsource')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_app.verse')),
            ],
            options={
                'unique_together': {('verse', 'source')},
            },
        ),
    ]
