# Generated by Django 5.2.8 on 2026-08-28 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surahaudio',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='quran_app.surah'),
        ),
        migrations.AddField(
            model_name='verse',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran_app.surah'),
        ),
        migrations.AddField(
            model_name='studentrecitation',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_app.verse'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('surah', 'number')},
        ),
    ]
