# Generated by Django 5.2.8 on 2025-12-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurahAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_ar', models.CharField(max_length=100)),
                ('reciter_en', models.CharField(max_length=100)),
                ('rewaya_ar', models.CharField(max_length=100)),
                ('rewaya_en', models.CharField(max_length=100)),
                ('server', models.URLField()),
                ('audio_url', models.URLField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='quran_app.surah')),
            ],
        ),
    ]
